# Generated by Django 4.2.28 on 2026-02-08 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_path', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('registered', 'Registered'), ('signing', 'Signing'), ('signed', 'Signed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('sigex_document_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(max_length=12)),
                ('full_name', models.CharField(max_length=255)),
                ('signer_type', models.CharField(choices=[('individual', 'Individual'), ('legal_entity', 'Legal Entity')], default='individual', max_length=20)),
                ('bin', models.CharField(blank=True, default='', max_length=12)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignatureModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('signer_iin', models.CharField(max_length=12)),
                ('signer_name', models.CharField(max_length=255)),
                ('signer_type', models.CharField(choices=[('individual', 'Individual'), ('legal_entity', 'Legal Entity')], default='individual', max_length=20)),
                ('signer_bin', models.CharField(blank=True, max_length=12, null=True)),
                ('signer_company', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_data', models.TextField(blank=True, default='')),
                ('sigex_sign_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='persistence.documentmodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('signing', 'Signing'), ('signed', 'Signed'), ('partially_signed', 'Partially Signed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentmodel',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='persistence.packagemodel'),
        ),
    ]
