# Generated by Django 4.2.28 on 2026-02-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='signed_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
