# Generated by Django 4.2.28 on 2026-02-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_documentmodel_signed_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
