# Generated by Django 4.2.28 on 2026-02-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0003_add_error_message_to_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmodel',
            name='signature_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
